### ISSUE TITLE
An end-to-end test case exists

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-oss-suite-release#40]
An end-to-end test case exists using the pinned component versions for: 
-  Conjur OSS 
- Conjur Helm Chart 
- Kubernetes authenticator 
- Secretless

**Comment by doodlesbykumbi** [comment]
The PR is merged. It'll be used as a foundation for further work. There are some issues that have yet to be addressed:
1. Logging that clearly informs the user what's going on e.g. What is being deployed, What test is being exercised and how. This needs to be very high level and absent of clutter.
2. Add adequate comments so that if a consumer of these test cases needs to look at the code it is more-easily navigable.
